steps:
  - name: 'maven:3.9-eclipse-temurin-21'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'
    dir: 'backend'
    id: 'build-quarkus-jar'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/shotlist-tool-backend:$COMMIT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'
    id: 'build-docker-image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/shotlist-tool-backend:$COMMIT_SHA']
    id: 'push-docker-image'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'shotlist-tool-backend-service'
      - '--image=gcr.io/$PROJECT_ID/shotlist-tool-backend:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
    id: 'deploy-to-cloud-run'

availableSecrets:
  secretManager:
    - env: 'AUTH0SECRET'
      versionName: 'projects/$PROJECT_NUMBER/secrets/AUTH0SECRET/versions/latest'
    - env: 'DB_URL'
      versionName: 'projects/$PROJECT_NUMBER/secrets/DB_URL/versions/latest'
    - env: 'DB_USERNAME'
      versionName: 'projects/$PROJECT_NUMBER/secrets/DB_USERNAME/versions/latest'
    - env: 'DB_PASSWORD'
      versionName: 'projects/$PROJECT_NUMBER/secrets/DB_PASSWORD/versions/latest'

images:
  - 'gcr.io/$PROJECT_ID/shotlist-tool-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
